Added :cascade op to drop any object recursively.
Ignore-this: c30f340ba5a5e17c4bf21218ae4dac91

'DROP TABLE p_channels;
NOTICE:  constraint p_channels_history_p_channel_id_fkey on table
p_channels_history depends on table p_channels
channels
ERROR:  cannot drop table p_channels because other objects depend on it
HINT:  Use DROP ... CASCADE to drop the dependent objects too.'
The error message and a hint described above suggested this patch.